# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

global:
    exp_name: 'test-ngp-nerf'

optimizer:
    optimizer_type: 'adam'
    lr: 0.001
    rgb_loss: 1.0

dataset:
    dataset_type: 'multiview'
    multiview_dataset_format: 'standard'
    num_rays_sampled_per_img: 4096
    mip: 2
    bg_color: 'white'

renderer:
    tracer_type: 'MyPackedRFTracer'
    num_steps: 512
    raymarch_type: ray
    render_batch: 8192  # 4096
    camera_origin:
        - -3.0
        - 0.65
        - -3.0
    shading_mode: 'rb'
    render_res:
        - 1024
        - 1024

trainer:
    trainer_type: 'MyTrainerSD'
    epochs: 100
    batch_size: 1
    model_format: 'full'
    valid_every: 50
    save_every: 10
    prune_every: 10 # iterations
    render_tb_every: 10

grid:
    grid_type: 'HashGrid'
    interpolation_type: 'linear'
    multiscale_type: 'cat'
    feature_dim: 4  # 4
    feature_std: 0.01
    num_lods: 16
    tree_type: 'geometric'
    max_grid_res: 4096  # 4096
    codebook_bitwidth: 19

net:
    nef_type: 'MyNeuralRadianceField'
    hidden_dim: 64
    num_layers: 1
    out_dim: 7
    position_input: True

embedder:
    pos_multires: 10
    view_multires: 4

my_nef:
    pos_embedder: 'positional'
    view_embedder: 'spherical'
    use_blob: True
    blob_scale: 5.0
    blob_width: 0.3
    bottleneck_dim: 8

my_optimizer:
    orientation_loss: 0.05
    predicted_normal_loss: 0.1 # 0.05
    opacity_loss: 0.002
    entropy_loss: 0.002
    albedo_steps: 1000
    diffusion_loss: 1.0
    warmup_iterations: 0
    init_lr: 0.1
    end_lr: 0.5
    reg_warmup_iterations: 0 #1000
    reg_init_lr: 0.1
    coarse_ratio: 0.5

my_diffusion:
    repo_id: 'stabilityai/stable-diffusion-2-1-base'
    diffusion_type: 'StableDiffusion'
    prompt: 'a 3D render of a birthday cake with candles'
    negative_prompt: ''
    guidance_scale: 100
    diffusion_bg_color: 'noise'

my_camera:
    num_novel_views_per_gt: 0
    num_novel_views_base: 100
    coarse_resolution: 64
    fine_resolution: 256
    light_distance_range:
        - 1.0 # 0.8
        - 1.5 # 1.5
    camera_distance_range:
        - 1.1 # 1.0
        - 1.5 # 1.5
    azimuth_range:
        - 0
        - 360
    polar_range:
        - 0
        - 100
    camera_angle_range:
        - 25
        - 42
    focal_length_multiplier_range:
        - 1.0 # 0.7
        - 2.0 # 1.35
    camera_offset: 0.1
    camera_up_std: 0.02
    look_at_std: 0.1