# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

global:
    exp_name: 'test-ngp-nerf'

optimizer:
    optimizer_type: 'adam'
    lr: 0.001
    rgb_loss: 1.0

dataset:
    dataset_type: 'multiview'
    multiview_dataset_format: 'standard'
    num_rays_sampled_per_img: 4096
    mip: 2
    bg_color: 'white'

renderer:
    tracer_type: 'MyPackedRFTracer'
    num_steps: 512
    raymarch_type: ray
    render_batch: 4000
    camera_origin:
        - -3.0
        - 0.65
        - -3.0
    shading_mode: 'rb'
    render_res:
        - 1024
        - 1024

trainer:
    trainer_type: 'MyTrainerSD'
    epochs: 50
    batch_size: 1
    model_format: 'full'
    valid_every: 50
    save_every: 10
    prune_every: 100 # iterations
    render_tb_every: 10

grid:
    grid_type: 'HashGrid'
    interpolation_type: 'linear'
    multiscale_type: 'cat'
    feature_dim: 2
    feature_std: 0.01
    num_lods: 16
    #base_lod: 4
    tree_type: 'geometric'
    max_grid_res: 2048
    codebook_bitwidth: 19

net:
    nef_type: 'MyNeuralRadianceField'
    hidden_dim: 128
    num_layers: 1
    out_dim: 4
    position_input: True

embedder:
    pos_multires: 10
    view_multires: 4

my_nef:
    pos_embedder: 'positional'
    view_embedder: 'spherical'
    use_blob: True
    blob_scale: 5.0
    blob_width: 0.2

my_optimizer:
    orientation_loss: 0.03
    predicted_normal_loss: 0.03
    opacity_loss: 0.00 #1
    entropy_loss: 0.00 #2
    albedo_steps: 1000
    diffusion_loss: 5.0

my_diffusion:
    repo_id: 'stabilityai/stable-diffusion-2-1-base'
    diffusion_type: 'StableDiffusion'
    prompt: 'a DSLR photo of a hamburger'
    negative_prompt: ''
    guidance_scale: 100

my_camera:
    num_novel_views_per_gt: 0
    num_novel_views_base: 100
    diffusion_resolution: 64
    light_distance_range:
        - 1.6
        - 3.0
    camera_distance_range:
        - 2.5
        - 3.0
    azimuth_range:
        - 0
        - 360
    elevation_range:
        - -10
        - 90
    camera_angle_range:
        - 25
        - 40
    focal_length_multiplier_range:
        - 0.7
        - 1.35
    camera_offset: 0.1
    camera_up_std: 0.02
    look_at_std: 0.2